server:
  port: 8080
spring:
  application:
    name: MultiTenant
  datasource:
    url: "jdbc:firebirdsql:localhost/3050:/SEC/BANCO/WSACESSO/WSACESSO.FDB?encoding=UTF8"
    username: "SYSDBA"
    password: "masterkey"
    driver-class-name: org.firebirdsql.jdbc.FBDriver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    database-platform: org.hibernate.dialect.FirebirdDialect
  main:
    allow-circular-references: true
